### PR TITLE
Fixes #39 Reformatting the code according to PEP style 

### LINKED ISSUE #39: Reformatting the code according to PEP style guide.
The code in check _addon.py, check_repo.py and common.py needs to be reformatted according to PEP 8 style guide along with some improvements in code like removing unnecessary parenthesis.
Please let me know if this sounds reasonable and I can start working on a pull for this!
Regards
Aditya

### PR DESCRIPTION
**Pull request by AdityaGupta030697**
Fixes #39
made changes according to PEP style guide and added .idea/ to gitignore.

### CODE REVIEW

**Comment by Razzeee** [comment]
Thx 🎉

**Comment by AdityaGupta030697** [comment]
Sir, can I have your email id? I have a few questions regarding the project
Regards
Aditya

**Comment by MartijnKaijser** [comment]
@AdityaGupta030697 you can create an account on forum.kodi.tv and ask you questions there

**Comment by AdityaGupta030697** [comment]
Sure

**Pull request merged**
