### PR TITLE
PEP 8 All Code

### PR DESCRIPTION
**Pull request by mzfr**
This will check for the pep8 violation.
Also I have fixed all the errors that were there in code base.

@Razzeee Should I change the value of length parameter from 120 to soemthing less or is it OK ?

### CODE REVIEW

**Comment by Razzeee** [comment]
Can you check how bad the default line lenght would be? So how many violations would we have with the default value of 79

**Comment by mzfr** [comment]
ok sure I'll do that

**Comment by mzfr** [comment]
@Razzeee after running pycodestyle at default value of 79 I got these errors 
```
check_repo.py:39:80: E501 line too long (99 > 79 characters)
check_repo.py:46:80: E501 line too long (88 > 79 characters)
check_repo.py:51:80: E501 line too long (88 > 79 characters)
check_addon.py:43:80: E501 line too long (112 > 79 characters)
check_addon.py:52:80: E501 line too long (81 > 79 characters)
check_addon.py:53:80: E501 line too long (86 > 79 characters)
check_addon.py:84:80: E501 line too long (82 > 79 characters)
check_addon.py:98:80: E501 line too long (102 > 79 characters)
check_addon.py:99:80: E501 line too long (95 > 79 characters)
check_addon.py:100:80: E501 line too long (105 > 79 characters)
check_addon.py:101:80: E501 line too long (108 > 79 characters)
check_addon.py:102:80: E501 line too long (80 > 79 characters)
check_addon.py:125:80: E501 line too long (85 > 79 characters)
check_addon.py:140:80: E501 line too long (82 > 79 characters)
check_addon.py:159:80: E501 line too long (96 > 79 characters)
check_addon.py:165:80: E501 line too long (87 > 79 characters)
check_addon.py:175:80: E501 line too long (98 > 79 characters)
check_addon.py:182:80: E501 line too long (113 > 79 characters)
check_addon.py:220:80: E501 line too long (96 > 79 characters)
check_addon.py:221:80: E501 line too long (97 > 79 characters)
check_addon.py:223:80: E501 line too long (108 > 79 characters)
check_addon.py:226:80: E501 line too long (95 > 79 characters)
check_addon.py:234:80: E501 line too long (113 > 79 characters)
check_addon.py:237:80: E501 line too long (95 > 79 characters)
check_addon.py:243:80: E501 line too long (115 > 79 characters)
check_addon.py:257:80: E501 line too long (91 > 79 characters)
check_addon.py:266:80: E501 line too long (111 > 79 characters)
check_addon.py:273:80: E501 line too long (80 > 79 characters)
check_addon.py:286:80: E501 line too long (118 > 79 characters)
check_addon.py:289:80: E501 line too long (109 > 79 characters)
check_addon.py:290:80: E501 line too long (82 > 79 characters)
check_addon.py:291:80: E501 line too long (97 > 79 characters)
check_addon.py:295:80: E501 line too long (82 > 79 characters)
check_addon.py:296:80: E501 line too long (97 > 79 characters)
check_addon.py:311:80: E501 line too long (109 > 79 characters)
check_addon.py:322:80: E501 line too long (108 > 79 characters)
check_addon.py:331:80: E501 line too long (113 > 79 characters)
common.py:19:80: E501 line too long (91 > 79 characters)
```

**Comment by Razzeee** [comment]
I would say fix them. Better then having to do that later.

**Comment by mzfr** [comment]
@Razzeee I think we should keep the line length to 120 or at least at 100.  There are many points where just breaking the line would either break the code or won't look nice.
Example:
on [line 174](https://github.com/xbmc/addon-check/blob/master/check_addon.py#L174) we have this if statement which have 98 characters. similarly we have another if statement on  [line 43](https://github.com/xbmc/addon-check/blob/master/check_addon.py#L43).

What do you think ?

**Comment by Razzeee** [comment]
Sure, I can then merge this right?

**Comment by mzfr** [comment]
yes you can

**Comment by Rechi** [comment]
@mzfr please rebase and squash first

**Comment by mzfr** [comment]
@Razzeee I have squash all the commits

**Comment by Razzeee** [comment]
Nice, would have done that on merge anyway :)

**Pull request merged**
