### PR TITLE
Configurable file exclusions

### PR DESCRIPTION
**Pull request by anxdpanic**
To address #156 , and possibly applies to #123

Allow for environment flexibility
```
--exclude-file              files/folders to exclude from permissions and file extension checks
--exclude-file-ext          file extensions to exclude from permissions and file extension checks
--whitelist-file            files/folders to exclude from file extension checks
--whitelist-file-ext        file extensions to exclude from file extension checks
```

### CODE REVIEW

**Comment by Razzeee** [comment]
Personally I feel this is too flexible. Configs for the three (?) usecases we support should be pretty similar on each project.
And it will be a pain to setup/configure.

I would like to hear @Rechi about this.

**Comment by anxdpanic** [comment]
I went this flexible mainly due to addon-ci vs addon local checks, where you'd want to ignore pyo/pyc and ide files/folders for local checks and not for addon-ci. Saves trying to cover all ide's and unique environments explicitly.

local:
```
kodi-addon-checker e:\Workspace\GitHub\plugin.video.youtube --branch=isengard --exclude-file-ext pyo pyc --exclude-file e:\Workspace\GitHub\plugin.video.youtube\.idea --whitelist-file GPL-2.0-only
```
ci:
```
kodi-addon-checker . --branch=isengard --whitelist-file GPL-2.0-only kodi-addon-checker.log
```

**Comment by anxdpanic** [comment]
Should I just close this and #160 instead of rebasing?

**Comment by Razzeee** [comment]
Yes, please do. Sorry for the confusion.

**Pull request closed without merging**
