### PR TITLE
Add Omega branches

### PR DESCRIPTION
**Pull request by fuzzard**
Hope this is ok @enen92 . let me know if ive missed something, or just flat out did something wrong.

### CODE REVIEW

**Review by enen92 — APPROVED** [review]
Yes looks correct (my fault on the add-on API for nexus). Note that we usually don't accept addons into Dev branches until pretty close to release (and sometimes even only after release). 
There's no advantage currently for people to submit to omega

**Comment by enen92** [comment]
On a sidenote can you also update ghactions to look into omega as well?
https://github.com/xbmc/addon-check/blob/master/.github/workflows/check-kodi-repos.yml#L15

**Comment by enen92** [comment]
Also, tests on the CI are failing because the repo-generator is not yet generating the gz file for omega: 
http://mirrors.kodi.tv/addons/omega/addons.xml.gz

I guess that PR needs to be merged before considering this one

**Comment by fuzzard** [comment]
Updated the check-kodi-repos.yml

**Comment by enen92** [comment]
Actions are green, merging

**Pull request merged**
