### PR TITLE
Added: Reject add-ons targeting Python 2.

### PR DESCRIPTION
**Pull request by basrieter**
Added a check that prevents add-ons targetting Python 2.

### CODE REVIEW

**Review by romanvm — APPROVED** [review]

**Comment by basrieter** [comment]
Who can  update the PyPi package?

**Comment by razzeee** [comment]
enen, rechi, me

**Comment by basrieter** [comment]
Great! Does any of you have time to push a new version to PyPi?

**Comment by basrieter** [comment]
@enen92 @Rechi and/or @razzeee does anyone have time to push the checker to PyPi?

**Comment by enen92** [comment]
@basrieter https://pypi.org/project/kodi-addon-checker/0.0.32/
You could probably be added as a maintainer as well

**Comment by basrieter** [comment]
That certainly would be an option. But thanks for the posting.

**Pull request merged**
