### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by Razzeee**
Please give your blessings by posting here @Rechi @mzfr @AdityaGupta030697

### CODE REVIEW

**Comment by mzfr** [comment]
Yeah, I'm fine with this. Please go ahead!

**Comment by Razzeee** [comment]
@Rechi @AdityaGupta030697 
I'm not 100% sure that thumbs up works in this case.
Please confirm with a post/comment.

**Comment by AdityaGupta030697** [comment]
Sure, Go ahead!

**Comment by Rechi** [comment]
fine for me

**Pull request merged**
