### PR TITLE
XML/JSON Correctly check for file extension

### PR DESCRIPTION
**Pull request by pannal**
Fixes issue #275 

* Correctly check for file extension instead of looking for an extension anywhere in the full filename

### CODE REVIEW

**Comment by razzeee** [comment]
Looks correct to me

**Comment by romanvm** [comment]
@razzeee  Who should merge it?

**Comment by romanvm** [comment]
@razzeee Who should publish the latest version of the checker? This PR is blocked because the checker cannot pass: https://github.com/xbmc/repo-scripts/pull/2645

**Comment by razzeee** [comment]
done

**Pull request merged**
