### PR TITLE
Standardize Python package

### PR DESCRIPTION
**Pull request by slgobinath**
This PR standardizes addon-check according to Python package format. With this PR, users can install `kodi-addon-checker` using `python setup.py install` or `pip install kodi-addon-checker` after publishing it to [PyPi](https://pypi.python.org/pypi)

Related issue: https://github.com/xbmc/addon-check/issues/45

Tested on Linux Mint 18.3 (Python 3.5.2)  and Windows 10 (Python 3.6.2)

### CODE REVIEW

**Comment by Rechi** [comment]
The command is called `kodi-addon-checker`, but what it actually does is check a whole repo.
Can this be improved to have two commands (check repo & check addon)?

**Comment by slgobinath** [comment]
In this PR I did not want to break the consistency. My plan was automating repo/addon folder detection.

For example, if the user is in a repo folder, it should check the complete repository. If the user is in addon folder, it should check for the addon. However, I postponed this to implement with command line interface (which will be my next PR).

Also, I will change the `kodi-addon-checker` to receive the folder to scan as an argument rather than using the current directory.
WDYT?

**Comment by slgobinath** [comment]
I agree with you on executing from the current directory.

However, I find having two executable files is redundant (`kodi-addon-checker` and `kodi-repo-checker`)
I find two problems wit this:
1. In Windows, Python scripts are not executable. So we need two separate modules to provide `py -m ....` kind of execution. (I am not a Windows user. Please correct me if I am wrong)
2. Users need to choose which one to execute (little usability overhead)

WDYT about automatic folder detection?
If we find `addon.xml` in the current directory, treat it as an addon, if not treat it as a repo. If you prefer, we can print the mode at the beginning.
Eg: `Found xxxxxxxx plugin` or `Found xxxxxxxx repository`

As an alternative, we can ask users to configure it using command line argument but it will require the user to pick an option which is again a usability overhead.

**Comment by mzfr** [comment]
I too feel that we shouldn't have two separate executables.

BTW, the current code behavior is:

1. If no path is passed, then run in "repo mode" - treating all top level folders in the current directory as separate addons.
2. If one or more paths are passed then:
    2.1 Read config file from current directory 
    2.2 Treat all paths as separate addons and check all of them

Maybe it's just me, but I've grown used to this model (of passing multiple paths etc.)

So, if we change this to detect at runtime whether a path is a repo/addon then we'll have to make sure we that we also allow for multiple paths.

**Comment by romanvm** [comment]
> In Windows, Python scripts are not executable. So we need two separate modules to provide py -m .... kind of execution. (I am not a Windows user. Please correct me if I am wrong)

Not quite so. The current setuptools automatically bundles an .exe file for the script to be launched, that is,
```python
entry_points={'console_scripts': ['kodi-addon-checker = kodi_addon_checker.__main__:main']}
```
will produce `kodi-addon-checker.exe` in Scripts folder.

**Comment by Razzeee** [comment]
If we can safely find a way to autodetect it, I'm all for it, as it lowers the bar for useage.

Still it would probably be best for our CI to pass multiple paths directly, for addon checks.

**Comment by Razzeee** [comment]
API looks good, would be helpful if the help text points out the difference of repo vs addon check. Haven't looked at the code yet.

**Comment by slgobinath** [comment]
New help description:
```
usage: kodi-addon-checker [-h] [--version] [add-on [add-on ...]]

Checks Kodi repo for best practices and creates problem and warning reports.
If optional add-on directories are provided, check only those add-ons.
Otherwise, scan current repository and check all add-ons in the current
directory.

positional arguments:
  add-on      optional add-on directories

optional arguments:
  -h, --help  show this help message and exit
  --version   show program's version number and exit
```
Please let me know if the wordings have to be improved.

Now add-on directory arguments are also checked for addon.xml file. If it does not exist, argparse will throw an error.

**Comment by slgobinath** [comment]
Hi,
Please check my new commits.

> I just need to check what the repos will do when they automatically get the new version

Do you mean the `kodi-addon-checker` version in PyPi?

**Comment by Razzeee** [comment]
No, as we don't have that yet.
What we do at the moment is update via git and call the py file. Which will not work anymore I think or maybe we can provide an "executable" py file.
For e.g. https://github.com/xbmc/repo-scripts/blob/helix/.travis.yml

**Comment by slgobinath** [comment]
For this problem, I recommend publishing kodi-addon-checker to [PyPi](https://pypi.python.org/pypi), then install it using `pip install kodi-addon-checker` and access it as a command line tool.

```
...
script:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then kodi-addon-checker; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then kodi-addon-checker $(git diff --diff-filter=d --name-only HEAD~ | grep / | cut -d / -f1 | sort | uniq); fi'
...
```

However, there is a quick fix as well (Tested in my computer):
1. Include `.tests` directory to `PYTHONPATH`
    ```
    export PYTHONPATH="$PYTHONPATH:./.tests"
    ```
2. Run add-on checker as a Python module
    ```
    python -m kodi_addon_checker
    ```

**Comment by Razzeee** [comment]
Pushed to pypi
https://pypi.org/project/kodi-addon-checker/
Seems like it does not like markdown? Upload guide said to try https://github.com/pypa/readme_renderer first, which I did not do.

**Comment by slgobinath** [comment]
Thanks. I will fix the markdown issue.

**Comment by slgobinath** [comment]
Sure thing. I will do that after #64 because it will help us to have separate reports per repository.

**Pull request merged**
